My:
    Protocal: "tcp"
    serverIP: ":1234"
    HostAddress: ":1234"

MSSQL:
    ConnectionString: "server=CTV-PARALLEL5.Production.CTV.ca;user id=DevLogin;password=LoginDev1!;database=VideoWeb"

RabbitMQ:
    Scheme: "amqp"
    Host:   "10.123.14.200"
    Port:   5672
    User:   "mtsservice"
    Password: "var10us!@#$"
    Vhost: "agincourt"
    Qname: "raymond.superdispatcher.requests"

Log: '{
    "level": "debug",
    "encoding": "json",
    "outputPaths": ["stdout", "logs/log.txt"],
    "encoderConfig": {
        "levelKey": "level",
        "timeKey": "timestamp"
        "messageKey": "message",
        "levelEncoder": "lowercase"
    }
  }'